name: Build OpenCO2_Mini

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - uses: arduino/compile-sketches@v1
        with:
          fqbn: "esp32:esp32:esp32s3"
          platforms: |
            - name: esp32:esp32
              source-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
              version: 3.3.4
          libraries: |
            - name: Adafruit NeoPixel
            - name: Sensirion Core
            - name: Sensirion I2C STCC4
            - name: Sensirion UPT BLE Server
          sketch-paths: |
            - .